# Generated by Django 4.2.7 on 2023-11-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_final", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("descrição", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="Category",
            field=models.ManyToManyField(to="site_final.category"),
        ),
    ]
