# Generated by Django 4.2.7 on 2023-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_final', '0008_perfil_instagram_alter_perfil_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='instagram',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
