# Generated by Django 4.2.7 on 2023-11-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_final', '0012_alter_salademensagens_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='servico',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='sala_de_mensagens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_final.salademensagens'),
        ),
    ]
