# Generated by Django 4.2.7 on 2023-11-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_final', '0013_remove_mensagem_servico_mensagem_sala_de_mensagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='sala_de_mensagens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_final.salademensagens'),
        ),
    ]
