# Generated by Django 4.2.7 on 2023-11-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_final', '0014_alter_mensagem_sala_de_mensagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='salademensagens',
            name='identificador_sala',
            field=models.CharField(default='seila', max_length=100),
        ),
    ]
