# Generated by Django 4.2.7 on 2023-12-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_final", "0017_propostaservico"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="dias_de_trabalho",
            field=models.CharField(
                choices=[
                    ("seg", "Segunda-feira"),
                    ("ter", "Terça-feira"),
                    ("qua", "Quarta-feira"),
                    ("qui", "Quinta-feira"),
                    ("sex", "Sexta-feira"),
                    ("sab", "Sábado"),
                    ("dom", "Domingo"),
                ],
                default="seg",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="horario_entrada",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AddField(
            model_name="perfil",
            name="horario_saida",
            field=models.TimeField(default="18:00"),
        ),
    ]
