# Generated by Django 4.2.7 on 2023-12-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_final", "0018_perfil_dias_de_trabalho_perfil_horario_entrada_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaDaSemana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("seg", "Segunda-feira"),
                            ("ter", "Terça-feira"),
                            ("qua", "Quarta-feira"),
                            ("qui", "Quinta-feira"),
                            ("sex", "Sexta-feira"),
                            ("sab", "Sábado"),
                            ("dom", "Domingo"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="perfil", name="dias_de_trabalho",),
        migrations.AddField(
            model_name="perfil",
            name="dias_de_trabalho",
            field=models.ManyToManyField(blank=True, to="site_final.diadasemana"),
        ),
    ]
