# Generated by Django 4.2.7 on 2023-12-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_final", "0019_diadasemana_remove_perfil_dias_de_trabalho_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diadasemana", name="dia", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="dias_de_trabalho",
            field=models.ManyToManyField(to="site_final.diadasemana"),
        ),
    ]
