# Generated by Django 4.2.7 on 2023-12-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_final", "0020_alter_diadasemana_dia_alter_perfil_dias_de_trabalho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diadasemana",
            name="dia",
            field=models.CharField(
                choices=[
                    ("seg", "Segunda-feira"),
                    ("ter", "Terça-feira"),
                    ("qua", "Quarta-feira"),
                    ("qui", "Quinta-feira"),
                    ("sex", "Sexta-feira"),
                    ("sab", "Sábado"),
                    ("dom", "Domingo"),
                ],
                max_length=50,
            ),
        ),
    ]
