# Generated by Django 4.2.7 on 2023-12-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_final", "0021_alter_diadasemana_dia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diadasemana",
            name="dia",
            field=models.CharField(
                choices=[
                    ("Segunda", "Segunda"),
                    ("Terça", "Terça"),
                    ("Quarta", "Quarta"),
                    ("Quinta", "Quinta"),
                    ("Sexta", "Sexta"),
                    ("Sábado", "Sábado"),
                    ("Domingo", "Domingo"),
                ],
                max_length=50,
            ),
        ),
    ]
